server:
  port: 8189
  servlet:
    context-path:
spring:
#  jpa:
 #   show-sql: true
  #  properties:
   #   hibernate:
    #    dialect: org.hibernate.dialect.PostgreSQL95Dialect
     #   temp:
      #    use_jdbc_metadata_defaults: false

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notes_db
    username: postgres
    password: Cacs7Tndf3#
